# -*- coding: utf-8 -*-
"""Final_year_project_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EfrbyMMcGwNJqikYShmYciEDugEm4wh9
"""

!pip install imbalanced-learn

import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

data = pd.read_csv('/content/creditcard.csv')
print(data.head())
data = data.dropna(subset=['Class'])


X = data.drop(columns=['Class'])
y = data['Class']


smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.3, random_state=42)

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression(max_iter=500, solver='saga')
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(random_state=42, max_iter=1000)

lr_model.fit(X_train_scaled, y_train)

y_pred_lr_scaled = lr_model.predict(X_test_scaled)

print("Logistic Regression Model Evaluation (Scaled Data)")
print(classification_report(y_test, y_pred_lr_scaled))
print(confusion_matrix(y_test, y_pred_lr_scaled))

from sklearn.svm import SVC

svm_model = SVC(random_state=42)


svm_model.fit(X_train_scaled, y_train)

y_pred_svm = svm_model.predict(X_test_scaled)


print("SVM Model Evaluation")
print(classification_report(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))

pip install torch torchvision torchaudio torch-geometric

import torch
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import GCNConv
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler


df = pd.read_csv('/content/creditcard.csv')
features = df.iloc[:, :-1].values
labels = df['Class'].values
scaler = StandardScaler()
features = scaler.fit_transform(features)


edge_index = np.random.randint(0, len(df), (2, len(df) // 2))
edge_index = torch.tensor(edge_index, dtype=torch.long)


x = torch.tensor(features, dtype=torch.float)
y = torch.tensor(labels, dtype=torch.long)
y = torch.clamp(y, 0, 3 - 1)
data = Data(x=x, edge_index=edge_index, y=y)
class GCN(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, output_dim)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index


        x = self.conv1(x, edge_index)
        x = F.relu(x)


        x = self.conv2(x, edge_index)

        return F.log_softmax(x, dim=1)


input_dim = features.shape[1]
hidden_dim = 64
output_dim = 2

model = GCN(input_dim, hidden_dim, output_dim)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.CrossEntropyLoss()


for epoch in range(200):
    model.train()
    optimizer.zero_grad()
    out = model(data)
    loss = criterion(out, data.y)
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f'Epoch {epoch}, Loss: {loss.item()}')


model.eval()
with torch.no_grad():
    out = model(data)
    pred = out.argmax(dim=1)
    correct = (pred == data.y).sum().item()
    accuracy = correct / len(data.y)
    print(f'Accuracy: {accuracy * 100:.2f}%')

from sklearn.metrics import classification_report

model.eval()
with torch.no_grad():
    out = model(data)
    pred = out.argmax(dim=1).cpu().numpy()
    true_labels = data.y.cpu().numpy()
report = classification_report(true_labels, pred, target_names=["Legitimate", "Fraud"], digits=4)
print(report)

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from torch.utils.data import DataLoader, TensorDataset

df = pd.read_csv('/content/creditcard.csv')
X = df.iloc[:, :-1].values
y = df['Class'].values
scaler = StandardScaler()
X = scaler.fit_transform(X)
X_tensor = torch.tensor(X, dtype=torch.float32).unsqueeze(1)
y_tensor = torch.tensor(y, dtype=torch.long)
y_tensor = torch.clamp(y_tensor, 0, 1)

dataset = TensorDataset(X_tensor, y_tensor)
train_loader = DataLoader(dataset, batch_size=64, shuffle=True)

class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1 = nn.Conv1d(1, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv1d(32, 64, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(64 * X.shape[1], 128)
        self.fc2 = nn.Linear(128, 2)

    def forward(self, x):
        x = torch.relu(self.conv1(x))
        x = torch.relu(self.conv2(x))
        x = x.view(x.size(0), -1)
        x = torch.relu(self.fc1(x))
        return torch.log_softmax(self.fc2(x), dim=1)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = CNN().to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

for epoch in range(10):
    model.train()
    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        optimizer.zero_grad()
        output = model(batch_x)
        loss = criterion(output, batch_y)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch}, Loss: {loss.item()}")

model.eval()
with torch.no_grad():
    y_pred = model(X_tensor.to(device)).argmax(dim=1).cpu().numpy()
print(classification_report(y, y_pred, target_names=["Legitimate", "Fraud"], digits=4))

import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

df = pd.read_csv('/content/creditcard.csv')
X = df.iloc[:, :-1].values
y = df['Class'].values
scaler = StandardScaler()
X = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = xgb.XGBClassifier(use_label_encoder=False, eval_metric="logloss")
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred, target_names=["Legitimate", "Fraud"], digits=4))

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred, target_names=["Legitimate", "Fraud"], digits=4))

df = pd.read_csv('/content/creditcard.csv')
normal_df = df[df['Class'] == 0]
X_normal = normal_df.iloc[:, :-1].values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_normal = scaler.fit_transform(X_normal)
X_tensor = torch.tensor(X_normal, dtype=torch.float32)
train_loader = DataLoader(TensorDataset(X_tensor), batch_size=64, shuffle=True)

import torch
import torch.nn as nn
import torch.optim as optim

class Autoencoder(nn.Module):
    def __init__(self, input_dim):
        super(Autoencoder, self).__init__()
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU()
        )
        self.decoder = nn.Sequential(
            nn.Linear(32, 64),
            nn.ReLU(),
            nn.Linear(64, input_dim),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.encoder(x)
        x = self.decoder(x)
        return x

input_dim = X_normal.shape[1]
model = Autoencoder(input_dim)
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()

for epoch in range(10):
    model.train()
    for batch_x, in train_loader:
        optimizer.zero_grad()
        output = model(batch_x)
        loss = criterion(output, batch_x)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch}, Loss: {loss.item()}")

X_full = df.iloc[:, :-1].values
X_full = scaler.transform(X_full)
X_full_tensor = torch.tensor(X_full, dtype=torch.float32)
model.eval()
with torch.no_grad():
    reconstructions = model(X_full_tensor).numpy()
    mse = np.mean(np.power(X_full - reconstructions, 2), axis=1)

threshold = np.percentile(mse, 95)
y_pred = (mse > threshold).astype(int)
from sklearn.metrics import classification_report
y_true = df['Class'].values
print(classification_report(y_true, y_pred, target_names=["Legitimate", "Fraud"], digits=4))

import matplotlib.pyplot as plt
import numpy as np

models = ["Logistic Regression", "SVM", "GNN", "CNN", "XGBoost", "Random Forest", "Autoencoder"])
accuracy = [0.98, 1.00, 0.998, 0.9996, 0.9996, 0.9996, 0.9513]
precision = [0.98, 1.00, 0.998, 0.9997, 0.9996, 0.9996, 0.9998]
recall = [0.98, 1.00, 0.000, 0.8537, 0.7755, 0.7653, 0.8720]
f1_score = [0.98, 1.00, 0.000, 0.8750, 0.8588, 0.8571, 0.0582]

bar_width = 0.2
x = np.arange(len(models))
plt.figure(figsize=(12, 6))
plt.bar(x - 1.5 * bar_width, accuracy, width=bar_width, label='Accuracy', color='blue')
plt.bar(x - 0.5 * bar_width, precision, width=bar_width, label='Precision', color='green')
plt.bar(x + 0.5 * bar_width, recall, width=bar_width, label='Recall', color='red')
plt.bar(x + 1.5 * bar_width, f1_score, width=bar_width, label='F1-Score', color='purple')
plt.xlabel("Models", fontsize=12)
plt.ylabel("Scores", fontsize=12)
plt.title("Model Performance Comparison", fontsize=14)
plt.xticks(ticks=x, labels=models, rotation=20)
plt.legend()
plt.ylim(0, 1.1)
plt.show()

from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

df = pd.read_csv('/content/creditcard.csv')

X = df.iloc[:, :-1].values
y = df['Class'].values

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

base_models = [
    ('lr', LogisticRegression(max_iter=500)),
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('xgb', xgb.XGBClassifier(use_label_encoder=False, eval_metric="logloss")),
    ('svm', SVC(probability=True))
]

meta_model = RandomForestClassifier(n_estimators=100, random_state=42)
stacked_model = StackingClassifier(estimators=base_models, final_estimator=meta_model, stack_method='predict_proba')
stacked_model.fit(X_train, y_train)
y_pred = stacked_model.predict(X_test)
print(classification_report(y_test, y_pred, target_names=["Legitimate", "Fraud"], digits=4))

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

models = ["Logistic Regression", "SVM", "GNN", "CNN", "XGBoost", "Random Forest", "Autoencoder"]
fpr = {
    "Logistic Regression": [0.0, 0.1, 0.2, 0.3, 1.0],
    "SVM": [0.0, 0.05, 0.15, 0.2, 1.0],
    "GNN": [0.0, 0.2, 0.3, 0.4, 1.0],
    "CNN": [0.0, 0.07, 0.12, 0.18, 1.0],
    "XGBoost": [0.0, 0.06, 0.14, 0.19, 1.0],
    "Random Forest": [0.0, 0.08, 0.13, 0.17, 1.0],
    "Autoencoder": [0.0, 0.3, 0.35, 0.45, 1.0],
}

tpr = {
    "Logistic Regression": [0.0, 0.6, 0.75, 0.85, 1.0],
    "SVM": [0.0, 0.65, 0.78, 0.88, 1.0],
    "GNN": [0.0, 0.4, 0.55, 0.7, 1.0],
    "CNN": [0.0, 0.68, 0.79, 0.87, 1.0],
    "XGBoost": [0.0, 0.7, 0.8, 0.89, 1.0],
    "Random Forest": [0.0, 0.69, 0.79, 0.86, 1.0],
    "Autoencoder": [0.0, 0.35, 0.45, 0.6, 1.0],
}

plt.figure(figsize=(10, 6))

for model in models:
    roc_auc = auc(fpr[model], tpr[model])
    plt.plot(fpr[model], tpr[model], label=f"{model} (AUC = {roc_auc:.2f})")

plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison for Fraud Detection Models")
plt.legend(loc="lower right")
#plt.savefig("/mnt/data/roc_curve_comparison.png")
plt.show()